# Change these first
owner: gikiapp # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: giki.app
    url: https://giki.app
  - name: giki.app/api/ping
    url: https://giki.app/api/ping
  - name: POST giki.app/api/talks
    url: https://giki.app/api/talks
    method: POST
    headers:
      - "Authorization: Bearer ${GIKI_BOT_TOKEN}"
      - "Content-Type: application/json"
    body: '{"text": "hello world - status"}'
  - name: GET giki.app/api/talks
    url: https://giki.app/api/talks?user_name=i
    method: GET
    headers:
      - "Authorization: Bearer ${GIKI_BOT_TOKEN}"
      - "Content-Type: application/json"
  - name: GET giki.app/api/users
    url: https://giki.app/api/users?name=i
    method: GET
    headers:
      - "Authorization: Bearer ${GIKI_BOT_TOKEN}"
      - "Content-Type: application/json"
  - name: GET giki.app/api/user/login
    url: https://giki.app/api/user/login
    headers:
      - "Authorization: Bearer ${GIKI_BOT_TOKEN}"
      - "Content-Type: application/json"
    body: '{"provider": "weibo", "providerUserId": "123", "scene": "giki_app_web"}'

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: status
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://giki.app/favico.ico
  name: Giki•叽喳 Service Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/gikiapp/status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
